version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: logistics_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: logistics_otd
    ports:
      - "3307:3306"   
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: logistics_app
    depends_on:
      - mysql
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  mysql_data: