create database sql_supplychain;
use sql_supplychain;
CREATE TABLE `order_delivery_analysis` (
    `Type` VARCHAR(20) NOT NULL,
    `Days for shipping (real)` INT NOT NULL,
    `Days for shipment (scheduled)` INT NOT NULL,
    `Benefit per order` DECIMAL(10, 4) NOT NULL,
    `Sales per customer` DECIMAL(12, 4) NOT NULL,
    `Delivery Status` VARCHAR(50) NOT NULL,
    `Late_delivery_risk` TINYINT(1) NOT NULL, 
    `Category Id` INT NOT NULL,
    `Category Name` VARCHAR(100) NOT NULL,
    `Customer City` VARCHAR(100) NOT NULL,
    `Customer Country` VARCHAR(100) NOT NULL,
    `Customer Email` VARCHAR(100) DEFAULT NULL,
    `Customer Fname` VARCHAR(50) NOT NULL,
    `Customer Id` INT NOT NULL,
    `Customer Lname` VARCHAR(50) NOT NULL,
    `Customer Password` VARCHAR(100) DEFAULT NULL,
    `Customer Segment` VARCHAR(50) NOT NULL,
    `Customer State` VARCHAR(10) NOT NULL,
    `Customer Street` VARCHAR(255) NOT NULL,
    `Customer Zipcode` INT DEFAULT NULL,
    `Department Id` INT NOT NULL,
    `Department Name` VARCHAR(100) NOT NULL,
    `Latitude` DECIMAL(10, 8) NOT NULL,
    `Longitude` DECIMAL(11, 8) NOT NULL,
    `Market` VARCHAR(50) NOT NULL,
    `Order City` VARCHAR(100) NOT NULL,
    `Order Country` VARCHAR(100) NOT NULL,
    `Order Customer Id` INT NOT NULL,
    `order date (DateOrders)` DATETIME NOT NULL, 
    `Order Id` INT NOT NULL,
    `Order Item Cardprod Id` INT NOT NULL,
    `Order Item Discount` DECIMAL(10, 4) NOT NULL,
    `Order Item Discount Rate` DECIMAL(5, 4) NOT NULL,
    `Order Item Id` INT NOT NULL PRIMARY KEY, 
    `Order Item Product Price` DECIMAL(10, 2) NOT NULL,
    `Order Item Profit Ratio` DECIMAL(5, 4) NOT NULL,
    `Order Item Quantity` INT NOT NULL,
    `Sales` DECIMAL(12, 2) NOT NULL,
    `Order Item Total` DECIMAL(12, 4) NOT NULL,
    `Order Profit Per Order` DECIMAL(10, 4) NOT NULL,
    `Order Region` VARCHAR(100) NOT NULL,
    `Order State` VARCHAR(100) NOT NULL,
    `Order Status` VARCHAR(50) NOT NULL,
    `Order Zipcode` INT DEFAULT NULL,
    `Product Card Id` INT NOT NULL,
    `Product Category Id` INT NOT NULL,
    `Product Description` TEXT DEFAULT NULL, 
    `Product Image` VARCHAR(255) NOT NULL,
    `Product Name` VARCHAR(155) NOT NULL,
    `Product Price` DECIMAL(10, 2) NOT NULL,
    `Product Status` TINYINT(1) NOT NULL,
    `shipping date (DateOrders)` DATETIME NOT NULL, 
    `Shipping Mode` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

